// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceFaturamento.Data;

#nullable disable

namespace ServiceFaturamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418060859_INicialFaturamento")]
    partial class INicialFaturamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceFaturamento.Models.ItemNota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoProduto")
                        .HasColumnType("text");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("integer");

                    b.Property<int?>("NotaId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotaId");

                    b.ToTable("ItensNota");
                });

            modelBuilder.Entity("ServiceFaturamento.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("ServiceFaturamento.Models.ItemNota", b =>
                {
                    b.HasOne("ServiceFaturamento.Models.Nota", "Nota")
                        .WithMany("Itens")
                        .HasForeignKey("NotaId");

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("ServiceFaturamento.Models.Nota", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
